### ISSUE TITLE
How to add new device?

### ISSUE THREAD

**Issue by markyskus** [t0bst4r/matterbridge-home-assistant-addon#53]
I try this awesome add-on, working like a charm, faster then the HomeKit bridge
but how could I add new devices? in the add-on config I added the new device, restart the add-on but I don't see it in HomeKit and I don't find anything on the web gui

**Comment by t0bst4r** [comment]
Could you please add details of your addon config? Screenshot or yaml / json.
Could you also add details of the entity which is missing? Entity Id, is it hidden in Ha?

**Comment by bedge117** [comment]
@markyskus can you see it in the matterbridge devices?  Go to your http://ip_address:8283/devices

If they are listed there, and not in HomeKit, it is an issue between HomeKit and the Matterbridge and not from HA to Matterbridge.

**Comment by markyskus** [comment]
@bedge117 yes, I see there, I wrote it, and I didn't say the problem is with HA and the add-on connection :)
Just asking what to do, reboot the HomeKit hub?

**Comment by bedge117** [comment]
Oh!  sorry @markyskus  I completely misread that.  

If a reboot doesn't work, you may have to go through the process of adding the matter device again.  That is, if a reboot doesn't find them.

**Comment by t0bst4r** [comment]
Please post an update if everything is working and close the issue. 🙂

**Comment by markyskus** [comment]
@t0bst4r just delete the bridge from HomeKit and repairing it with all devices
other question, now I see there is an update for the home assistant plugin (current 1.0) how could I update this? when I click on it:
error - [18:13:22.136] [Matterbridge]: Failed to start child process: spawn sudo ENOENT
error - [18:13:22.136] [Matterbridge]: Error installing plugin matterbridge-home-assistant
error - [18:13:22.136] [Matterbridge]: Child process stdio streams have closed with code -2

**Comment by t0bst4r** [comment]
Could you add more context? Some more logs before and after that? What did you exactly do to produce that error?

**Comment by markyskus** [comment]
<img width="1470" alt="Képernyőfotó 2024-06-19 - 21 35 20" src="https://github.com/t0bst4r/matterbridge-home-assistant-addon/assets/13024360/9ce93dcd-ba81-485d-a199-1fd957a4de01">

**Comment by markyskus** [comment]
this 3 error line is after clicking on the update plugin button

**Comment by t0bst4r** [comment]
Okay, I see. 
Please do not use that button for now. That is currently not working. I’ll build the new addon version for 1.3.0 in the next one or two days. Then you can update using the Addon Update flow in home assistant.

**Comment by t0bst4r** [comment]
I created a new issue #57
