### ISSUE TITLE
Versions are confusing

### ISSUE THREAD

**Issue by siobhanellis** [t0bst4r/matterbridge-home-assistant-addon#56]
## Problem

> When using the UI for Matterbridge, the versions can be confusing. I've just installed the latest version from the repository. Yet is says that I'm running V1.0.0 and latest is V1.2.0, and on top of the page it says current is 1.2.22 and latest is 1.3.0

## Expected behavior

> Consistant in versions

## Actual behavior

> explained above

## Steps to reproduce

> Installed latest version and started
![Screenshot 2024-06-19 at 17 03 05](https://github.com/t0bst4r/matterbridge-home-assistant-addon/assets/33163141/0edf0d06-41ed-44c4-bd98-28ef52c76162)

## Proposed changes

> If you already know how to fix it, provide the details. They will help us.

**Comment by t0bst4r** [comment]
Yes, i am working on that to harmonize it

**Comment by t0bst4r** [comment]
i have setup automated versioning.
this addon will always have the same version as `matterbridge-home-assistant`, but suffixed with the version number.

E.g.:
- `matterbridge-home-assistant` has version `1.3.2`
- this addon gets the version `1.3.2-64`

The version shown at the top (in your screenshot `current v1.2.22 latest v1.3.0`) is the version of matterbridge itself, which is not under my control.
