### ISSUE TITLE
Add-on will not start

### ISSUE THREAD

**Issue by robnnson** [t0bst4r/matterbridge-home-assistant-addon#59]
## Problem

The Matterbridge add-on will not start.

## Expected behavior

For the add-on to start and web gui is accessible.

## Actual behavior

Add-on fails to start with the following logs:

```
-----------------------------------------------------------
 Add-on: Matterbridge
 Populate your Home Assistant instance as Matter Bridge
-----------------------------------------------------------
 Add-on version: 1.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.4  (amd64 / qemux86-64)
 Home Assistant Core: 2024.6.3
 Home Assistant Supervisor: 2024.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
#############################
CURRENT CLIENT CONFIGURATION:
{
  "includeDomains": [],
  "includePatterns": [],
  "excludeDomains": [],
  "excludePatterns": []
}
#############################

> matterbridge
> matterbridge -add ./node_modules/matterbridge-home-assistant

[04:00:31.150] [Matterbridge] Created Matterbridge Plugin Directory: /root/Matterbridge 
CLI: Matterbridge.loadInstance() failed with error: Error: [node-persist][readFile] /root/.matterbridge/storage/.matterbridge/c6724947ca70506d3d4794dd710813af1a1ef8e646852dba3fe0dea6a2aa7911 does not look like a valid storage file!

> matterbridge
> matterbridge -bridge

CLI: Matterbridge.loadInstance() failed with error: Error: [node-persist][readFile] /root/.matterbridge/storage/.matterbridge/c6724947ca70506d3d4794dd710813af1a1ef8e646852dba3fe0dea6a2aa7911 does not look like a valid storage file!
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

## Steps to reproduce

Attempt to start the add-on

## Proposed changes

N/A

**Comment by BrianKnudsen** [comment]
I have that problem too  but get this in the log

file:///app/node_modules/@project-chip/matter.js/dist/esm/cluster/server/ClusterServer.js:261
          throw new ImplementationError(
                ^

ImplementationError: Attribute minLevel is optional and not initialized. To use it please initialize it first.
    at ClusterServer.result.<computed> [as setMinLevelAttribute] (file:///app/node_modules/@project-chip/matter.js/dist/esm/cluster/server/ClusterServer.js:261:17)
    at LevelControlAspect.update (file:///app/node_modules/matterbridge-home-assistant/lib/devices/aspects/level-control-aspect.js:34:39)
    at ClimateDevice.updateState (file:///app/node_modules/matterbridge-home-assistant/lib/devices/home-assistant-device.js:21:26)
    at async HomeAssistantMatterAdapter.create (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:88:9)
    at async HomeAssistantMatterAdapter.expensiveUpdate (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-matter-adapter.js:42:13)
    at async HomeAssistantClient.expensiveUpdate (file:///app/node_modules/matterbridge-home-assistant/lib/home-assistant/home-assistant-client.js:50:13)

**Comment by t0bst4r** [comment]
@robnnson that‘s interesting. Could you try uninstalling and reinstalling the addon? It seems that the addon storage corrupted.

@BrianKnudsen this is related to a bug with climate devices. Please exclude the climate domain and try again. This bug is tracked there: t0bst4r/matterbridge-home-assistant#47

**Comment by helderfmf** [comment]
@robnnson had the same problem. 
Open file manager addon and go to 
/addon_configs/a1b84aa7_matterbridge/storage/.matterbridge/ 
Search for the file of the log, in my case the file was 0 bytes, so I deleted it and was recreated on startup.

Removing and installing the addon did not resolve the problem.

**Comment by robnnson** [comment]
> [helderfmf](/helderfmf)

This is strange...the only folder I have is /homeassistant/addons_config and the matterbridge addon isn't even listed in that...?

**Comment by helderfmf** [comment]
> > [helderfmf](/helderfmf)
> 
> This is strange...the only folder I have is /homeassistant/addons_config and the matterbridge addon isn't even listed in that...?
> 

You need to go above a level. 
/homeassistant is the default folder, but you can go up to / just hit the <- button.

**Comment by robnnson** [comment]
> > > [helderfmf](/helderfmf)
> > 
> > 
> > This is strange...the only folder I have is /homeassistant/addons_config and the matterbridge addon isn't even listed in that...?
> 
> You need to go above a level. /homeassistant is the default folder, but you can go up to / just hit the <- button.

Worked perfectly! Thanks!

**Comment by t0bst4r** [comment]
did it fix the problem? does it work now?

**Comment by robnnson** [comment]
> did it fix the problem? does it work now?

Sure did. Appreciate that a ton.

**Comment by enslaved2die** [comment]
> @robnnson had the same problem. Open file manager addon and go to /addon_configs/a1b84aa7_matterbridge/storage/.matterbridge/ Search for the file of the log, in my case the file was 0 bytes, so I deleted it and was recreated on startup.
> 
> Removing and installing the addon did not resolve the problem.

I cant get there wit the file editor addon. the back button doesnt work
