### ISSUE TITLE
duplicate devices

### ISSUE THREAD

**Issue by tammeryousef1006** [t0bst4r/matterbridge-home-assistant-addon#69]
kindly see the photo which shows some devices being duplicated 4 times 

![duplicates](https://github.com/t0bst4r/matterbridge-home-assistant-addon/assets/62266828/1fc812aa-46a1-41e8-adea-b6b787a72f6b)

**Comment by t0bst4r** [comment]
Why did you close it? Did anything change? What solved it?

**Comment by tammeryousef1006** [comment]
i had matter devices over sonoff integration  , the integration shows duplicate 4 channel for each device , that's caused the matterbridge to detect 4 devices of same one , so the detection in matterbridge correct that's why I closed it

**Comment by t0bst4r** [comment]
Okay, thanks for the details

**Comment by tammeryousef1006** [comment]
better to report true bugs , not things related to different issue to maintain the addon correctly
