### ISSUE TITLE
Sensors aren’t included in matter device list

### ISSUE THREAD

**Issue by sandeepb1** [t0bst4r/matterbridge-home-assistant-addon#80]
My configuration settings are blank to allow everything but no sensor entities from HA are being fed in to matterbridge. 

Does the add on support Sensors at this time?

**Comment by t0bst4r** [comment]
Sensors are not yet supported. 
I‘ve added a remark to the readme. 

Sensors were already requested in the main project (t0bst4r/matterbride-home-assistant#130). Lets track the status over there.

And @bassrock already started working on it (t0bst4r/matterbridge-home-assistant#118).
