### ISSUE TITLE
a second instance... Twice the goodness

### ISSUE THREAD

**Issue by Ian-Zz** [t0bst4r/matterbridge-home-assistant-addon#82]
I would like to run a second instance of this awesome add on.
I'm thinking one for Android one for Alexa/Echo etc. I tried forking and creating my own local repo and add it to my HA addon folder.
I also edited files (probably hap hazerdly - I'm not a real coder in the least) tried to change install locations-names. homebridge-my for example. Also port numbers. The my add on just wont start. Ports are one issue. Just wondering if this is possible or even worth the bother. One is good. Two better? Thanks all.

**Comment by t0bst4r** [comment]
As of now the ports of this application are not configurable. Matterbridge doesn’t support that.
Since the Addon needs to run with host network mode, the ports are already blocked.
I’ll consider this in the future but i will not address this in the near future.
