### ISSUE TITLE
adding battery percentage to selected devices

### ISSUE THREAD

**Issue by tammeryousef1006** [t0bst4r/matterbridge-home-assistant-addon#86]
### Domain

lock

### What is actually missing?

hi there , is it possible to view the battery percentage with the device at matterbridge ? because I pair already a lock but need its battery reading too .

thanks in advance

**Comment by t0bst4r** [comment]
Does it have an attribute for the battery percentage, or does it have an extra entity for it?

**Comment by tammeryousef1006** [comment]
Yes of course

**Comment by tammeryousef1006** [comment]
![lock](https://github.com/t0bst4r/matterbridge-home-assistant-addon/assets/62266828/fef408c9-c8e1-4fc4-b89a-5ef2140263d8)

**Comment by t0bst4r** [comment]
Okay I see. It’s not an attribute. It’s another entity (with its own entity_id). At the moment each entity is handled on its own. No link is created between different entities of the same device. 
That what you actually need.

we already started the same discussion [over there in the main project](t0bst4r/matterbridge-home-assistant#130). Let’s keep it simple and only track it once (over there).
