### ISSUE TITLE
Connect to both HomeKit and Alexa?

### ISSUE THREAD

**Issue by jak1502** [t0bst4r/matterbridge-home-assistant-addon#90]
Is it possible to connect with both HomeKit and Alexa? I've connected to matter bridge via HomeKit fine but Alexa is saying I need another join code?

**Comment by jvmahon** [comment]
Yes, you should be able to connect to multiple controllers.
You can't re-use the same QR code.

What you have to do is to generate another code from a controller that is already paired, in this case, from within iOS.

In iOS go to "Home Settings", then go to "Home Hubs & Bridges" and then select the MaterBridge bridge. You should then see an option to generate another pairing code - select that and use that with Alexa

**Comment by jak1502** [comment]
Thank you very much!

**Comment by jvmahon** [comment]
PS - This is common for all Matter pairings, including "normal" (not bridged) Matter Devices. You can only use the QR code for the first pairing; after that, you generate new codes using an already-paired controller.
