### ISSUE TITLE
Lights with dimming capability showing up as wrong device type

### ISSUE THREAD

**Issue by smallett01** [t0bst4r/matterbridge-home-assistant-addon#91]
### What happened?

Lights with dimming capability are showing up with device type of (0x0100) rather than (0x0101). This means other systems only see the light as an 'on/off' light 

### Version

1.3.9

**Comment by JarydX** [comment]
This seems to be a similar issue I experience: In Google Home App I can dimm all dimmable lights, but in voice control with Google Assistent the lights are only seen as On-Off lights.

**Comment by southwestflavorz** [comment]
I'm also having this issue. I'm passing my dimmable and sometimes rgb capable lights to smartthings, however they show up as on/off lights only.

**Comment by t0bst4r** [comment]
Thank you for reporting that.

I am currently working on a larger refactoring of the project. With that, I will fix this bug as well. But it will take me one or two weeks to do it.

**Comment by t0bst4r** [comment]
This should be fixed with version `2.0.3-96`
