### ISSUE TITLE
[Bug]: Google Assistant cant find dimmable Lamps

### ISSUE THREAD

**Issue by enslaved2die** [t0bst4r/matterbridge-home-assistant-addon#97]
### What happened?

Weirdly everything is integrated in Google Home and I can set the brightness as I like but when I use Google Assistant I always get the respond that there are not dimmable Lamps avaiable. I can set the color and toggle the lamps no problem.

### Version

1.6.12-86

**Comment by t0bst4r** [comment]
Actually it's a duplicate of #91 . Closing this one to track it over there.
