### ISSUE TITLE
[Bug]: Lamps with only color temperature have no option to change the temperature in Google Home

### ISSUE THREAD

**Issue by enslaved2die** [t0bst4r/matterbridge-home-assistant-addon#98]
### What happened?

Lamps like Ikea Tradfri E27 1055 lm that only have color temperature instead of full color spectrum dont have the ability to change the color temperature in Google Home. 
Lamps that have full color can change the temperature no problem.

### Version

1.6.12-86

**Comment by enslaved2die** [comment]
![Screenshot_20240717-123131](https://github.com/user-attachments/assets/e0b2b71a-448e-41f0-8e30-1a356795479f)
![Screenshot_20240717-123141](https://github.com/user-attachments/assets/cd623b46-2d8e-4074-8254-3da58a8142ff)
A few screenshots you can see that the "Wohnzimmer" Lamp dont have the options for the color temperature while the full color spectrum lamp in the "Flur" has the option.

**Comment by t0bst4r** [comment]
Yes, this is a known bug, which was already reported in the main repository.
I'll close this one, and track the status over there.

https://github.com/t0bst4r/matterbridge-home-assistant/issues/146

**Comment by enslaved2die** [comment]
> Yes, this is a known bug, which was already reported in the main repository. I'll close this one, and track the status over there.
> 
> [t0bst4r/matterbridge-home-assistant#146](https://github.com/t0bst4r/matterbridge-home-assistant/issues/146)

Oh yeah sure, I make sure that next time I make bug reports there :)
Sorry for the inconvenience

**Comment by t0bst4r** [comment]
Not a problem. It's not your reponsibility to check both repos. 
I am currently doing a larger refactoring of the main project, which takes some time. After that I'll have this bug implicitly fixed.
Additionally i want to merge both projects to only have one issue tracker 😄
