### ISSUE TITLE
[Feature]: Specify Matterbridge UI Port in Addon Config

### ISSUE THREAD

**Issue by Omnipius** [t0bst4r/matterbridge-home-assistant-addon#99]
### What is actually missing?

Provide a way to specify the port used by the Matterbridge Web UI from within the HA Addon Configuration. 

This can be done by passing the assigned port number to option `-frontend` when launching Matterbridge:

`matterbridge -bridge -frontend [port number]`

**Comment by t0bst4r** [comment]
What is this actually needed for?

**Comment by Omnipius** [comment]
This would allow for running multiple instances of MB to segregate devices exposed to different Matter controllers. 

Running multiple instances of the matterbridge-home-assistant-addon plugin within MB in childbridge mode could achieve the same thing.

**Comment by t0bst4r** [comment]
Okay, but beside the frontend port, the matter port also needs to be changeable then (default 5540).

**Comment by t0bst4r** [comment]
I have that implemented. It will be available in `2.2.0` in the next 5 minutes or so.
